"""empty message

Revision ID: 84207b59b24b
Revises: 1cdc0a4d47b6
Create Date: 2023-06-07 14:55:37.683073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84207b59b24b'
down_revision = '1cdc0a4d47b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
